### PR TITLE
[Issue 4] Fixing multiwords command

### PR DESCRIPTION
**Pull request by vitorrm**
https://github.com/rhythminme/serverless-gulp/issues/4

### CODE REVIEW

**Comment by vitorrm** [comment]
@rhythminme with this fix we will be able to send commands like 'deploy function', 'config credentials' and so on

**Comment by murilodag** [comment]
@rajwilkhu do you have write access to this repository?

**Comment by rajwilkhu** [comment]
@vitorrm @murilodag merged and published. Sorry for the delay. Will check more often.

**Comment by murilodag** [comment]
Thank you @rajwilkhu

**Pull request merged**
